cc_test(
    name = "disruptor_queue_test",
    srcs = ["disruptor_queue_tests.cpp",
            "bit_utils_tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src:disruptor_queue"
    ],
)